version: "3.7"
networks:
  userspice:
    name: userspice
    driver: bridge
services:
  database_userspice:
    image: mysql:latest
    container_name: database_userspice
    ports:
      - '3306:3306'
    networks:
      - userspice
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: qwe123
    volumes:
      - ./dbdata/:/var/lib/mysql/
      - ./mysql-dump:/docker-entrypoint-initdb.d
  bussola:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    cap_add:
      - SYS_ADMIN
      - SYS_TIME
    environment:
      TZ: UTC
      COMPOSER_MEMORY_LIMIT: -1
    container_name: userspice
    volumes:
      - .:/var/www/html/:rw
    networks:
      - userspice
